"""initial schema

Revision ID: cf9965abc9a2
Revises: 
Create Date: 2026-10-09 09:52:19.801278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cf9965abc9a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_config_key'), 'business_config', ['key'], unique=True)
    op.create_table('market_items',
    sa.Column('type', sa.Enum('competitor_tariff', 'regulator', 'spectrum', name='market_item_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runbooks',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('failure_type', sa.String(length=100), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runbooks_failure_type'), 'runbooks', ['failure_type'], unique=False)
    op.create_table('settings',
    sa.Column('autonomy_level', sa.Enum('recommend_only', 'approve_to_act', 'auto_low_risk', name='autonomy_level'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('district', sa.String(length=255), nullable=False),
    sa.Column('uplink_link_id', sa.UUID(), nullable=True),
    sa.Column('energy_cost_azn_month', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('up', 'down', name='operational_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'engineer', 'account_manager', 'viewer', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.Enum('admin', 'engineer', 'account_manager', 'viewer', name='user_role'), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_entity'), 'audit_events', ['entity'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('cells',
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('technology', sa.Enum('4G', '5G', name='cell_technology'), nullable=False),
    sa.Column('revenue_per_min_azn', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('status', sa.Enum('up', 'down', name='operational_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cells_site_id'), 'cells', ['site_id'], unique=False)
    op.create_table('enterprise_customers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=255), nullable=False),
    sa.Column('account_manager_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_manager_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('from_site_id', sa.UUID(), nullable=False),
    sa.Column('to_site_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('fiber', 'microwave', name='link_type'), nullable=False),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('up', 'down', name='operational_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['to_site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # sites.uplink_link_id -> links.id, added here (not inline on sites) since
    # sites and links have a circular FK dependency and links didn't exist yet.
    op.create_foreign_key(
        'fk_sites_uplink_link_id', 'sites', 'links', ['uplink_link_id'], ['id']
    )
    op.create_table('contracts',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('enterprise_sla', 'tower_lease', 'interconnect', 'vendor_sla', name='contract_type'), nullable=False),
    sa.Column('restore_within_min', sa.Integer(), nullable=False),
    sa.Column('penalty_per_started_hour_azn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('penalty_cap_azn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('clause_text', sa.Text(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['enterprise_customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_customer_id'), 'contracts', ['customer_id'], unique=False)
    op.create_table('customer_sites',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.Enum('leased_line', 'private_apn', 'mobile', name='customer_service_type'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['enterprise_customers.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'site_id', 'service_type', name='uq_customer_site_service')
    )
    op.create_index(op.f('ix_customer_sites_customer_id'), 'customer_sites', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_sites_site_id'), 'customer_sites', ['site_id'], unique=False)
    op.create_table('incidents',
    sa.Column('root_cause_link_id', sa.UUID(), nullable=False),
    sa.Column('root_cause_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', name='incident_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eta_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['root_cause_link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriber_segments',
    sa.Column('cell_id', sa.UUID(), nullable=False),
    sa.Column('segment', sa.Enum('premium', 'standard', 'budget', name='subscriber_segment'), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('arpu_azn', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriber_segments_cell_id'), 'subscriber_segments', ['cell_id'], unique=False)
    op.create_table('subscribers',
    sa.Column('home_cell_id', sa.UUID(), nullable=False),
    sa.Column('segment', sa.Enum('premium', 'standard', 'budget', name='subscriber_segment'), nullable=False),
    sa.Column('msisdn_masked', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['home_cell_id'], ['cells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_home_cell_id'), 'subscribers', ['home_cell_id'], unique=False)
    op.create_table('actions',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('agent', sa.Enum('network', 'contracts', 'finance', 'commercial', name='action_agent'), nullable=False),
    sa.Column('proposal', sa.Text(), nullable=False),
    sa.Column('owner_role', sa.Enum('admin', 'engineer', 'account_manager', 'viewer', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'approved', 'rejected', 'executed', name='action_status'), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risk_level'), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_incident_id'), 'actions', ['incident_id'], unique=False)
    op.create_table('agent_outputs',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('agent', sa.Enum('network', 'contracts', 'finance', 'commercial', name='action_agent'), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.Enum('live', 'fallback', name='agent_output_source'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_outputs_incident_id'), 'agent_outputs', ['incident_id'], unique=False)
    op.create_table('alarms',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('cell_id', sa.UUID(), nullable=True),
    sa.Column('link_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'major', 'minor', 'warning', name='alarm_severity'), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarms_incident_id'), 'alarms', ['incident_id'], unique=False)
    op.create_index(op.f('ix_alarms_processed'), 'alarms', ['processed'], unique=False)
    op.create_index(op.f('ix_alarms_site_id'), 'alarms', ['site_id'], unique=False)
    op.create_index(op.f('ix_alarms_timestamp'), 'alarms', ['timestamp'], unique=False)
    op.create_index(op.f('ix_alarms_type'), 'alarms', ['type'], unique=False)
    op.create_table('incident_affected_sites',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'site_id', name='uq_incident_site')
    )
    op.create_index(op.f('ix_incident_affected_sites_incident_id'), 'incident_affected_sites', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_affected_sites_site_id'), 'incident_affected_sites', ['site_id'], unique=False)
    op.create_table('incident_timeline_events',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_timeline_events_incident_id'), 'incident_timeline_events', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_timeline_events_incident_id'), table_name='incident_timeline_events')
    op.drop_table('incident_timeline_events')
    op.drop_index(op.f('ix_incident_affected_sites_site_id'), table_name='incident_affected_sites')
    op.drop_index(op.f('ix_incident_affected_sites_incident_id'), table_name='incident_affected_sites')
    op.drop_table('incident_affected_sites')
    op.drop_index(op.f('ix_alarms_type'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_timestamp'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_site_id'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_processed'), table_name='alarms')
    op.drop_index(op.f('ix_alarms_incident_id'), table_name='alarms')
    op.drop_table('alarms')
    op.drop_index(op.f('ix_agent_outputs_incident_id'), table_name='agent_outputs')
    op.drop_table('agent_outputs')
    op.drop_index(op.f('ix_actions_incident_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_subscribers_home_cell_id'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_subscriber_segments_cell_id'), table_name='subscriber_segments')
    op.drop_table('subscriber_segments')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_customer_sites_site_id'), table_name='customer_sites')
    op.drop_index(op.f('ix_customer_sites_customer_id'), table_name='customer_sites')
    op.drop_table('customer_sites')
    op.drop_index(op.f('ix_contracts_customer_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_constraint('fk_sites_uplink_link_id', 'sites', type_='foreignkey')
    op.drop_table('links')
    op.drop_table('enterprise_customers')
    op.drop_index(op.f('ix_cells_site_id'), table_name='cells')
    op.drop_table('cells')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sites')
    op.drop_table('settings')
    op.drop_index(op.f('ix_runbooks_failure_type'), table_name='runbooks')
    op.drop_table('runbooks')
    op.drop_table('market_items')
    op.drop_index(op.f('ix_business_config_key'), table_name='business_config')
    op.drop_table('business_config')
    # ### end Alembic commands ###
